
server:
  port: 8080
  tomcat:
    max-threads: 800
    max-connections: 10000

spring:
  profiles:
    active: dev
  application:
    name: gateway-server
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        #后台管理系统
        - id: admin-server
          uri: lb://admin-server
          order: 1
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            # 熔断降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultfallback
        #用户模块
        - id: user-server
          uri: lb://user-server
          order: 1
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            # 熔断降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultfallback

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


